export const STATUS_COMANDA_IDS = { ABERTA: 1, FECHADA: 2, CANCELADA: 3 } as const
export const STATUS_PEDIDO_IDS = { AGUARDANDO_PREPARO: 1, EM_PREPARO: 2, PRONTO: 3, FINALIZADO: 4, CANCELADO: 5 } as const
export const STATUS_PAGAMENTO_IDS = { PENDENTE: 1, APROVADO: 2, CANCELADO: 3, ESTORNADO: 4 } as const
export const STATUS_NOTA_FISCAL_IDS = { AUTORIZADA: 1, CANCELADA: 2, ERRO: 3 } as const
export const STATUS_ASSINATURA_IDS = { PENDENTE: 1, PAGA: 2, EXPIRADA: 3, CANCELADA: 4 } as const
export const STATUS_HISTORICO_IDS = { APROVADO: 1, REJEITADO: 2 } as const
export const TIPO_MOVIMENTACAO_IDS = { ENTRADA: 1, SAIDA: 2, AJUSTE: 3 } as const
export const TIPO_DESCONTO_IDS = { VALOR: 1, PERCENTUAL: 2 } as const
