import { MigrationInterface, QueryRunner } from "typeorm";

export class NewStuff1776611501026 implements MigrationInterface {
    name = 'NewStuff1776611501026'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_0d0c575f48a4fe678173148156d\``);
        await queryRunner.query(`DROP INDEX \`IDX_432a96802564bf709ac8a16447\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`Observacoes_Geral\` \`Observacao\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` CHANGE \`created_at\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO_VARIACAO\` CHANGE \`created_at\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP COLUMN \`ID_Caixa\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP COLUMN \`Data_Vencimento\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP COLUMN \`preco_adicional\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD \`Status\` enum ('Pendente', 'Aprovado', 'Cancelado', 'Estornado') NOT NULL DEFAULT 'Aprovado'`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD \`ID_Usuario_Caixa\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`CPF\` varchar(14) NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD UNIQUE INDEX \`IDX_4123aaa602820747847ae86726\` (\`CPF\`)`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`Telefone\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`Endereco\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`Cidade\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`Estado\` varchar(2) NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD \`CEP\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`PLANO\` ADD \`Frequencia\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PLANO\` ADD \`Dia_Pagamento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PLANO\` ADD \`Mercado_Pago_Id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD \`Mercado_Pago_Id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD \`Data_Validade\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Telefone\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Endereco\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Metodos_Pagamento\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Autoatendimento_Ativo\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Status\` enum ('Ativo', 'Suspenso') NOT NULL DEFAULT 'Ativo'`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD \`Preco_Adicional\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD \`Status\` enum ('autorizada', 'erro', 'cancelada', 'pendente') NOT NULL DEFAULT 'autorizada'`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD \`Valor_Total\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD \`Data_Exclusao\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD \`ID_Pagamento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD UNIQUE INDEX \`IDX_53587e2175429674989f61da16\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Valor_Total\` \`Valor_Total\` decimal(10,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Valor_Taxa_Servico\` \`Valor_Taxa_Servico\` decimal(10,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Troco\` \`Troco\` decimal(10,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP COLUMN \`Codigo\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD \`Codigo\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP COLUMN \`Logotipo\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD \`Logotipo\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP COLUMN \`Observacao\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD \`Observacao\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP COLUMN \`Imagem\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD \`Imagem\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP COLUMN \`Status\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD \`Status\` enum ('Ativo', 'Inativo') NOT NULL DEFAULT 'Ativo'`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP COLUMN \`Imagem\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD \`Imagem\` longtext NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\` (\`ID_Estabelecimento\`, \`Codigo\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_bd6002cf64e5518daed0e85c68d\` FOREIGN KEY (\`ID_Usuario_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_de876b1390cccda1e12da86d522\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_53587e2175429674989f61da160\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_53587e2175429674989f61da160\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_de876b1390cccda1e12da86d522\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_bd6002cf64e5518daed0e85c68d\``);
        await queryRunner.query(`DROP INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP COLUMN \`Imagem\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD \`Imagem\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP COLUMN \`Status\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD \`Status\` varchar(30) NOT NULL DEFAULT 'Ativo'`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP COLUMN \`Imagem\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD \`Imagem\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP COLUMN \`Observacao\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD \`Observacao\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP COLUMN \`Logotipo\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD \`Logotipo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP COLUMN \`Codigo\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD \`Codigo\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Troco\` \`Troco\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Valor_Taxa_Servico\` \`Valor_Taxa_Servico\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`Valor_Total\` \`Valor_Total\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP INDEX \`IDX_53587e2175429674989f61da16\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP COLUMN \`ID_Pagamento\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP COLUMN \`ID_Estabelecimento\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP COLUMN \`Valor_Total\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP COLUMN \`Status\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP COLUMN \`Preco_Adicional\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Status\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Autoatendimento_Ativo\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Metodos_Pagamento\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Endereco\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP COLUMN \`Telefone\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP COLUMN \`Data_Validade\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP COLUMN \`Mercado_Pago_Id\``);
        await queryRunner.query(`ALTER TABLE \`PLANO\` DROP COLUMN \`Mercado_Pago_Id\``);
        await queryRunner.query(`ALTER TABLE \`PLANO\` DROP COLUMN \`Dia_Pagamento\``);
        await queryRunner.query(`ALTER TABLE \`PLANO\` DROP COLUMN \`Frequencia\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`CEP\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`Estado\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`Cidade\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`Endereco\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`Telefone\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP INDEX \`IDX_4123aaa602820747847ae86726\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP COLUMN \`CPF\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP COLUMN \`ID_Usuario_Caixa\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP COLUMN \`Status\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` DROP COLUMN \`Data_Exclusao\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD \`preco_adicional\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD \`Data_Vencimento\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD \`ID_Caixa\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO_VARIACAO\` CHANGE \`createdAt\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` CHANGE \`createdAt\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`Observacao\` \`Observacoes_Geral\` varchar(255) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_432a96802564bf709ac8a16447\` ON \`CUPOM_DESCONTO\` (\`ID_Cupom\`, \`Codigo\`)`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_0d0c575f48a4fe678173148156d\` FOREIGN KEY (\`ID_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
