import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatePlanTableV21778553279390 implements MigrationInterface {
    name = 'UpdatePlanTableV21778553279390'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`CARGO\` (\`ID_Cargo\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Permissoes_JSON\` json NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Cargo\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ESTOQUE_ITEM\` (\`ID_Estoque_Item\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Unidade_Medida\` varchar(255) NOT NULL, \`Quantidade_Atual\` int NOT NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Produto\` int NULL, UNIQUE INDEX \`REL_8c186d01380c5905737f56e848\` (\`ID_Produto\`), PRIMARY KEY (\`ID_Estoque_Item\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`MOVIMENTACAO_ESTOQUE\` (\`ID_Movimentacao\` int NOT NULL AUTO_INCREMENT, \`Justificativa\` varchar(255) NULL, \`Quantidade\` int NOT NULL, \`Tipo_Movimentacao\` varchar(255) NOT NULL, \`ID_Estoque_Item\` int NULL, \`ID_Usuario_Responsavel\` int NULL, PRIMARY KEY (\`ID_Movimentacao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PAGAMENTO_PEDIDO\` (\`ID_Pedido\` int NOT NULL, \`ID_Pagamento\` int NOT NULL, \`Observacoes_Cliente\` varchar(255) NULL, \`Quantidade\` int NOT NULL, \`Valor_Pago_Deste_Pedido\` decimal(10,2) NOT NULL, PRIMARY KEY (\`ID_Pedido\`, \`ID_Pagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PAGAMENTO\` (\`ID_Pagamento\` int NOT NULL AUTO_INCREMENT, \`Forma_Pagamento\` varchar(50) NOT NULL, \`Valor_Total\` decimal(10,2) NOT NULL DEFAULT '0.00', \`Valor_Taxa_Servico\` decimal(10,2) NOT NULL DEFAULT '0.00', \`Troco\` decimal(10,2) NOT NULL DEFAULT '0.00', \`Status\` enum ('Pendente', 'Aprovado', 'Cancelado', 'Estornado') NOT NULL DEFAULT 'Aprovado', \`Data_Hora_Pagamento\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Pedido_MercadoPago\` varchar(255) NULL, \`ID_Pagamento_MercadoPago\` varchar(255) NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Usuario_Caixa\` int NULL, PRIMARY KEY (\`ID_Pagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`USUARIO\` (\`ID_Usuario\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Email\` varchar(100) NOT NULL, \`Senha\` varchar(255) NOT NULL, \`Status\` varchar(255) NOT NULL DEFAULT 'Pendente', \`CPF\` varchar(14) NULL, \`Telefone\` varchar(20) NULL, \`Endereco\` varchar(255) NULL, \`Cidade\` varchar(100) NULL, \`Estado\` varchar(2) NULL, \`CEP\` varchar(10) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Cargo\` int NULL, UNIQUE INDEX \`IDX_b588f17ba2b208199bbaae42ae\` (\`Email\`), UNIQUE INDEX \`IDX_4123aaa602820747847ae86726\` (\`CPF\`), PRIMARY KEY (\`ID_Usuario\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PLANO\` (\`ID_Plano\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Valor_Plano\` decimal(10,2) NOT NULL, \`Frequencia\` varchar(20) NULL, \`Funcionalidades\` text NULL, PRIMARY KEY (\`ID_Plano\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ASSINATURA\` (\`ID_Assinatura\` int NOT NULL AUTO_INCREMENT, \`Data_Inicio\` date NOT NULL, \`Data_Vencimento_Prox\` date NOT NULL, \`Status\` varchar(255) NOT NULL, \`Ultima_Data_Pagamento\` date NULL, \`Recibo_URL\` varchar(255) NULL, \`ID_MercadoPago\` varchar(255) NULL, \`Valor\` decimal(10,2) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Plano\` int NULL, \`ID_Plano_Agendado\` int NULL, PRIMARY KEY (\`ID_Assinatura\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CUPOM_DESCONTO\` (\`ID_Cupom\` int NOT NULL AUTO_INCREMENT, \`Codigo\` varchar(50) NOT NULL, \`Tipo_Desconto\` varchar(20) NOT NULL, \`Valor_Desconto\` decimal(10,2) NOT NULL, \`Quantidade_Disponivel\` int NULL, \`Data_Validade\` date NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, UNIQUE INDEX \`UK_Estabelecimento_Codigo\` (\`ID_Estabelecimento\`, \`Codigo\`), PRIMARY KEY (\`ID_Cupom\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CONFIGURACAO_ESTABELECIMENTO\` (\`ID_Estabelecimento\` int NOT NULL, \`Cor_Fundo_Geral\` varchar(7) NULL, \`Cor_Cards\` varchar(7) NULL, \`Cor_Textos\` varchar(7) NULL, \`Cor_Botoes\` varchar(7) NULL, \`Texto_Botoes\` varchar(7) NULL, \`Cor_Categoria_Ativa\` varchar(7) NULL, \`Fonte\` varchar(50) NULL, \`Label_Comanda\` varchar(30) NULL, \`Logotipo\` longtext NULL, \`Permite_Observacoes\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`ID_Estabelecimento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CAIXA\` (\`ID_Caixa\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(255) NOT NULL, \`Mercado_Pago_Id\` varchar(255) NOT NULL, \`ID_Terminal\` varchar(255) NULL, \`Data_Hora_Criacao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Data_Hora_Delecao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Caixa\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ESTABELECIMENTO\` (\`ID_Estabelecimento\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`CNPJ\` varchar(18) NOT NULL, \`Telefone\` varchar(20) NULL, \`Endereco\` varchar(255) NULL, \`Metodos_Pagamento\` json NULL, \`Autoatendimento_Ativo\` tinyint NOT NULL DEFAULT 0, \`Status\` enum ('Ativo', 'Suspenso') NOT NULL DEFAULT 'Ativo', \`Codigo_Autoatendimento\` varchar(10) NULL, \`Formas_Atendimento_Habilitadas\` json NULL, \`Mercado_Pago_Id\` varchar(255) NULL, \`Pix_Estatico_Ativo\` tinyint NOT NULL DEFAULT 0, \`Pix_QR_Code_URL\` text NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Gerente_Responsavel\` int NULL, UNIQUE INDEX \`IDX_a15e54fa574124dbc4abd9650c\` (\`CNPJ\`), UNIQUE INDEX \`IDX_79dce4cf49163d518e9457f6b3\` (\`Codigo_Autoatendimento\`), UNIQUE INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` (\`ID_Gerente_Responsavel\`), PRIMARY KEY (\`ID_Estabelecimento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`COMANDA\` (\`ID_Comanda\` int NOT NULL AUTO_INCREMENT, \`Descricao\` varchar(100) NOT NULL, \`Nome_Cliente\` varchar(100) NULL, \`Status\` varchar(30) NOT NULL, \`Total\` decimal(10,2) NOT NULL, \`Valor_Desconto_Aplicado\` decimal(10,2) NULL, \`Tipo_Desconto_Aplicado\` varchar(30) NULL, \`Data_Abertura\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Usuario_Abertura\` int NULL, \`ID_Cupom_Aplicado\` int NULL, UNIQUE INDEX \`REL_67b2e47de00a6df9bce7b47862\` (\`ID_Usuario_Abertura\`), UNIQUE INDEX \`REL_9fb026ed877c74180d4210a080\` (\`ID_Cupom_Aplicado\`), PRIMARY KEY (\`ID_Comanda\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PEDIDO\` (\`ID_Pedido\` int NOT NULL AUTO_INCREMENT, \`Status\` varchar(30) NOT NULL, \`Observacao\` varchar(255) NULL, \`Cancelamento_Descricao\` varchar(255) NULL, \`Tipo_Atendimento\` varchar(30) NOT NULL, \`Custo_Adicional_Viagem\` decimal(10,2) NULL, \`seEntregue\` tinyint NOT NULL DEFAULT 0, \`Data_Hora_Chegada\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`ID_Comanda\` int NULL, \`ID_Estabelecimento\` int NULL, \`ID_Usuario_Cancelador\` int NULL, UNIQUE INDEX \`REL_5fea249bad2983b6781c52342f\` (\`ID_Usuario_Cancelador\`), PRIMARY KEY (\`ID_Pedido\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ItemPedido\` (\`ID_Item\` int NOT NULL AUTO_INCREMENT, \`ID_Pedido\` int NOT NULL, \`ID_Produto\` int NOT NULL, \`Observacoes_Cliente\` varchar(255) NULL, \`Quantidade\` int NOT NULL, \`Preco_Unitario_Momento\` decimal(10,2) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`ID_Item\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ItemPedidoVariacao\` (\`ID_Item_Produto\` int NOT NULL, \`ID_Variacao\` int NOT NULL, \`Preco_Adicional_Momento\` decimal(10,2) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`ID_Item_Produto\`, \`ID_Variacao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PRODUTO_VARIACAO\` (\`ID_Variacao\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Preco_Adicional\` decimal(10,2) NOT NULL, \`status\` varchar(30) NOT NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Produto\` int NULL, PRIMARY KEY (\`ID_Variacao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PRODUTO\` (\`ID_Produto\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Descricao\` varchar(255) NULL DEFAULT 1, \`Imagem\` longtext NULL, \`Estocavel\` tinyint NOT NULL, \`Preco_Base\` decimal(10,2) NOT NULL, \`Status\` enum ('Ativo', 'Inativo') NOT NULL DEFAULT 'Ativo', \`Data_Exclusao\` datetime(6) NULL, \`ID_Categoria\` int NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Produto\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CATEGORIA\` (\`ID_Categoria\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Imagem\` longtext NULL, \`Data_Exclusao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Categoria\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ADMIN\` (\`ID_Admin\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Email\` varchar(100) NOT NULL, \`Senha\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_c4da08b5c493a1e6b98e881ea8\` (\`Email\`), PRIMARY KEY (\`ID_Admin\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`NOTA_FISCAL\` (\`ID_Nota\` int NOT NULL AUTO_INCREMENT, \`Numero_Nota\` varchar(50) NOT NULL, \`CPF_CNPJ_Cliente\` varchar(18) NULL, \`Status\` enum ('autorizada', 'erro', 'cancelada', 'pendente') NOT NULL DEFAULT 'autorizada', \`Valor_Total\` decimal(10,2) NOT NULL, \`Data_Emissao\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Data_Exclusao\` datetime(6) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Pagamento\` int NULL, UNIQUE INDEX \`REL_53587e2175429674989f61da16\` (\`ID_Pagamento\`), PRIMARY KEY (\`ID_Nota\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`REFRESH_TOKEN\` (\`ID_Token\` int NOT NULL AUTO_INCREMENT, \`Token_Hash\` varchar(255) NOT NULL, \`Revogado\` tinyint NOT NULL DEFAULT 0, \`Expires_At\` datetime NOT NULL, \`ID_Usuario\` int NULL, \`ID_Admin\` int NULL, UNIQUE INDEX \`IDX_a209b8ccc27dbafbe560d67943\` (\`Token_Hash\`), PRIMARY KEY (\`ID_Token\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` ADD CONSTRAINT \`FK_94256e68a5d0c2294defa3f7022\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` ADD CONSTRAINT \`FK_8c186d01380c5905737f56e8489\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_acfd44433e0e71247c2c0f83605\` FOREIGN KEY (\`ID_Estoque_Item\`) REFERENCES \`ESTOQUE_ITEM\`(\`ID_Estoque_Item\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_57c345ee238785058affea4b5cd\` FOREIGN KEY (\`ID_Usuario_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_e1a1fa819701e6f06816a8b78c9\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_85ef99f6f9e459a32f2c2fd078a\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_7e6ba2c9056373e4c762799eaa3\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_bd6002cf64e5518daed0e85c68d\` FOREIGN KEY (\`ID_Usuario_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD CONSTRAINT \`FK_68069b6cef21c635907f6ce7991\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD CONSTRAINT \`FK_5ab96b45f71c286111960f800ce\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_49ffbd5130542196a401fb27386\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_06a24908fb114bdb90d20d9f7da\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_80fd6661ce54965db4388d9aa7f\` FOREIGN KEY (\`ID_Plano_Agendado\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`FK_577007b2f099c57ac0a959d2345\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD CONSTRAINT \`FK_a42abc8787974640c8df84198c6\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` ADD CONSTRAINT \`FK_14bdd214a3cb4aa00dc17c75869\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`FK_28e1d2575f8a94cc6b4264c57b1\` FOREIGN KEY (\`ID_Gerente_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_6fd5f78c80915b4c9ef90a62f40\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_67b2e47de00a6df9bce7b47862d\` FOREIGN KEY (\`ID_Usuario_Abertura\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_9fb026ed877c74180d4210a0805\` FOREIGN KEY (\`ID_Cupom_Aplicado\`) REFERENCES \`CUPOM_DESCONTO\`(\`ID_Cupom\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_a2419e69b50e597ce7e5a7df7e7\` FOREIGN KEY (\`ID_Comanda\`) REFERENCES \`COMANDA\`(\`ID_Comanda\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_722d10cf968f927fa833f539133\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_5fea249bad2983b6781c52342fa\` FOREIGN KEY (\`ID_Usuario_Cancelador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ItemPedido\` ADD CONSTRAINT \`FK_7065b36a8b4ed5c72a1d9bcb84c\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ItemPedido\` ADD CONSTRAINT \`FK_a97fee60c531ce9f715216c0920\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ItemPedidoVariacao\` ADD CONSTRAINT \`FK_937c4352dfb4806b820827e2640\` FOREIGN KEY (\`ID_Variacao\`) REFERENCES \`PRODUTO_VARIACAO\`(\`ID_Variacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ItemPedidoVariacao\` ADD CONSTRAINT \`FK_ad605708e2f717f64e464232e26\` FOREIGN KEY (\`ID_Item_Produto\`) REFERENCES \`ItemPedido\`(\`ID_Item\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD CONSTRAINT \`FK_1343219e116bbb26b6a5097d62c\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD CONSTRAINT \`FK_711a41c3de8cfee194fa18b00eb\` FOREIGN KEY (\`ID_Categoria\`) REFERENCES \`CATEGORIA\`(\`ID_Categoria\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD CONSTRAINT \`FK_3a113ffe3a2042755e54120f957\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD CONSTRAINT \`FK_c28aee109023f1b56998424532f\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_de876b1390cccda1e12da86d522\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_53587e2175429674989f61da160\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN\` ADD CONSTRAINT \`FK_a7cbe080d6269735502fbbcc725\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN\` ADD CONSTRAINT \`FK_bc2943b0a653bd83cf472e3a450\` FOREIGN KEY (\`ID_Admin\`) REFERENCES \`ADMIN\`(\`ID_Admin\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN\` DROP FOREIGN KEY \`FK_bc2943b0a653bd83cf472e3a450\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN\` DROP FOREIGN KEY \`FK_a7cbe080d6269735502fbbcc725\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_53587e2175429674989f61da160\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_de876b1390cccda1e12da86d522\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP FOREIGN KEY \`FK_c28aee109023f1b56998424532f\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP FOREIGN KEY \`FK_3a113ffe3a2042755e54120f957\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP FOREIGN KEY \`FK_711a41c3de8cfee194fa18b00eb\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP FOREIGN KEY \`FK_1343219e116bbb26b6a5097d62c\``);
        await queryRunner.query(`ALTER TABLE \`ItemPedidoVariacao\` DROP FOREIGN KEY \`FK_ad605708e2f717f64e464232e26\``);
        await queryRunner.query(`ALTER TABLE \`ItemPedidoVariacao\` DROP FOREIGN KEY \`FK_937c4352dfb4806b820827e2640\``);
        await queryRunner.query(`ALTER TABLE \`ItemPedido\` DROP FOREIGN KEY \`FK_a97fee60c531ce9f715216c0920\``);
        await queryRunner.query(`ALTER TABLE \`ItemPedido\` DROP FOREIGN KEY \`FK_7065b36a8b4ed5c72a1d9bcb84c\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_5fea249bad2983b6781c52342fa\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_722d10cf968f927fa833f539133\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_a2419e69b50e597ce7e5a7df7e7\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_9fb026ed877c74180d4210a0805\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_67b2e47de00a6df9bce7b47862d\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_6fd5f78c80915b4c9ef90a62f40\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_28e1d2575f8a94cc6b4264c57b1\``);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` DROP FOREIGN KEY \`FK_14bdd214a3cb4aa00dc17c75869\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_a42abc8787974640c8df84198c6\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`FK_577007b2f099c57ac0a959d2345\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_80fd6661ce54965db4388d9aa7f\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_06a24908fb114bdb90d20d9f7da\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_49ffbd5130542196a401fb27386\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP FOREIGN KEY \`FK_5ab96b45f71c286111960f800ce\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP FOREIGN KEY \`FK_68069b6cef21c635907f6ce7991\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_bd6002cf64e5518daed0e85c68d\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_7e6ba2c9056373e4c762799eaa3\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_85ef99f6f9e459a32f2c2fd078a\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_e1a1fa819701e6f06816a8b78c9\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_57c345ee238785058affea4b5cd\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_acfd44433e0e71247c2c0f83605\``);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` DROP FOREIGN KEY \`FK_8c186d01380c5905737f56e8489\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` DROP FOREIGN KEY \`FK_94256e68a5d0c2294defa3f7022\``);
        await queryRunner.query(`DROP INDEX \`IDX_a209b8ccc27dbafbe560d67943\` ON \`REFRESH_TOKEN\``);
        await queryRunner.query(`DROP TABLE \`REFRESH_TOKEN\``);
        await queryRunner.query(`DROP INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP TABLE \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`IDX_c4da08b5c493a1e6b98e881ea8\` ON \`ADMIN\``);
        await queryRunner.query(`DROP TABLE \`ADMIN\``);
        await queryRunner.query(`DROP TABLE \`CATEGORIA\``);
        await queryRunner.query(`DROP TABLE \`PRODUTO\``);
        await queryRunner.query(`DROP TABLE \`PRODUTO_VARIACAO\``);
        await queryRunner.query(`DROP TABLE \`ItemPedidoVariacao\``);
        await queryRunner.query(`DROP TABLE \`ItemPedido\``);
        await queryRunner.query(`DROP INDEX \`REL_5fea249bad2983b6781c52342f\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP TABLE \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`REL_9fb026ed877c74180d4210a080\` ON \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`REL_67b2e47de00a6df9bce7b47862\` ON \`COMANDA\``);
        await queryRunner.query(`DROP TABLE \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_79dce4cf49163d518e9457f6b3\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_a15e54fa574124dbc4abd9650c\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP TABLE \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP TABLE \`CAIXA\``);
        await queryRunner.query(`DROP TABLE \`CONFIGURACAO_ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP TABLE \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP TABLE \`ASSINATURA\``);
        await queryRunner.query(`DROP TABLE \`PLANO\``);
        await queryRunner.query(`DROP INDEX \`IDX_4123aaa602820747847ae86726\` ON \`USUARIO\``);
        await queryRunner.query(`DROP INDEX \`IDX_b588f17ba2b208199bbaae42ae\` ON \`USUARIO\``);
        await queryRunner.query(`DROP TABLE \`USUARIO\``);
        await queryRunner.query(`DROP TABLE \`PAGAMENTO\``);
        await queryRunner.query(`DROP TABLE \`PAGAMENTO_PEDIDO\``);
        await queryRunner.query(`DROP TABLE \`MOVIMENTACAO_ESTOQUE\``);
        await queryRunner.query(`DROP INDEX \`REL_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\``);
        await queryRunner.query(`DROP TABLE \`ESTOQUE_ITEM\``);
        await queryRunner.query(`DROP TABLE \`CARGO\``);
    }

}
