import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDb1781218840724 implements MigrationInterface {
    name = 'InitDb1781218840724'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`PERMISSAO\` (\`Nome\` varchar(50) NOT NULL, PRIMARY KEY (\`Nome\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CARGO\` (\`ID_Cargo\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Cargo\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ESTOQUE_ITEM\` (\`ID_Estoque_Item\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Unidade_Medida\` varchar(255) NOT NULL, \`Quantidade_Atual\` int NOT NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Produto\` int NULL, UNIQUE INDEX \`REL_8c186d01380c5905737f56e848\` (\`ID_Produto\`), PRIMARY KEY (\`ID_Estoque_Item\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`MOVIMENTACAO_ESTOQUE\` (\`ID_Movimentacao\` int NOT NULL AUTO_INCREMENT, \`Justificativa\` varchar(255) NULL, \`Quantidade\` int NOT NULL, \`Tipo_Movimentacao\` varchar(255) NOT NULL, \`ID_Estoque_Item\` int NULL, \`ID_Usuario_Responsavel\` int NULL, PRIMARY KEY (\`ID_Movimentacao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PAGAMENTO_PEDIDO\` (\`ID_Pedido\` int NOT NULL, \`ID_Pagamento\` int NOT NULL, \`Valor_Pago_Deste_Pedido\` decimal(10,2) NOT NULL, PRIMARY KEY (\`ID_Pedido\`, \`ID_Pagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`METODO_PAGAMENTO\` (\`ID_MetodoPagamento\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_58f21eb039d1bcfa59d4be7a0f\` (\`Nome\`), PRIMARY KEY (\`ID_MetodoPagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PAGAMENTO\` (\`ID_Pagamento\` int NOT NULL AUTO_INCREMENT, \`Valor_Total\` decimal(10,2) NOT NULL DEFAULT '0.00', \`Troco\` decimal(10,2) NOT NULL DEFAULT '0.00', \`Status\` enum ('Pendente', 'Aprovado', 'Cancelado', 'Estornado') NOT NULL DEFAULT 'Pendente', \`Data_Hora_Pagamento\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Pedido_MercadoPago\` varchar(255) NULL, \`ID_Pagamento_MercadoPago\` varchar(255) NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_MetodoPagamento\` int NULL, \`ID_Estabelecimento\` int NULL, \`ID_Usuario_Caixa\` int NULL, INDEX \`idx_pagamento_est_status_data\` (\`ID_Estabelecimento\`, \`Status\`, \`Data_Hora_Pagamento\`), PRIMARY KEY (\`ID_Pagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PERFIL_GERENTE\` (\`ID_Usuario\` int NOT NULL, \`CPF\` varchar(14) NULL, \`Endereco\` varchar(255) NULL, \`Cidade\` varchar(100) NULL, \`Estado\` varchar(2) NULL, \`CEP\` varchar(10) NULL, UNIQUE INDEX \`IDX_fc863aecc30115a2deffd1f674\` (\`CPF\`), PRIMARY KEY (\`ID_Usuario\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`USUARIO\` (\`ID_Usuario\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Email\` varchar(100) NOT NULL, \`Senha\` varchar(255) NOT NULL, \`Status\` varchar(255) NOT NULL DEFAULT 'Inativo', \`Password_Reset_Token\` varchar(255) NULL, \`Password_Reset_Expires\` timestamp NULL, \`Telefone\` varchar(20) NULL, \`Data_Criacao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Data_Exclusao\` timestamp(6) NULL, \`ID_Cargo\` int NULL, UNIQUE INDEX \`IDX_b588f17ba2b208199bbaae42ae\` (\`Email\`), PRIMARY KEY (\`ID_Usuario\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PLANO\` (\`ID_Plano\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Valor_Plano\` decimal(10,2) NOT NULL, \`Frequencia\` varchar(20) NULL, \`Funcionalidades\` text NULL, \`ID_MercadoPago_Plano\` varchar(255) NULL, PRIMARY KEY (\`ID_Plano\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ASSINATURA\` (\`ID_Assinatura\` int NOT NULL AUTO_INCREMENT, \`Data_Inicio\` date NOT NULL, \`Data_Vencimento_Prox\` date NOT NULL, \`Status\` varchar(255) NOT NULL, \`ID_MercadoPago\` varchar(255) NULL, \`Valor\` decimal(10,2) NULL, \`ID_Estabelecimento\` int NULL, \`ID_Plano\` int NULL, UNIQUE INDEX \`REL_49ffbd5130542196a401fb2738\` (\`ID_Estabelecimento\`), PRIMARY KEY (\`ID_Assinatura\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CUPOM_DESCONTO\` (\`ID_Cupom\` int NOT NULL AUTO_INCREMENT, \`Codigo\` varchar(50) NOT NULL, \`Tipo_Desconto\` varchar(20) NOT NULL, \`Valor_Desconto\` decimal(10,2) NOT NULL, \`Data_Validade\` date NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Estabelecimento\` int NULL, UNIQUE INDEX \`UK_Estabelecimento_Codigo\` (\`ID_Estabelecimento\`, \`Codigo\`), PRIMARY KEY (\`ID_Cupom\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CONFIGURACAO_ESTABELECIMENTO\` (\`ID_Estabelecimento\` int NOT NULL, \`Cor_Fundo_Geral\` varchar(7) NULL, \`Cor_Cards\` varchar(7) NULL, \`Cor_Textos\` varchar(7) NULL, \`Cor_Botoes\` varchar(7) NULL, \`Texto_Botoes\` varchar(7) NULL, \`Cor_Categoria_Ativa\` varchar(7) NULL, \`Fonte\` varchar(50) NULL, \`Label_Comanda\` varchar(30) NULL, \`Logotipo\` longtext NULL, \`Permite_Observacoes\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`ID_Estabelecimento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CAIXA\` (\`ID_Caixa\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(255) NOT NULL, \`Mercado_Pago_Id\` varchar(255) NOT NULL, \`ID_Terminal\` varchar(255) NULL, \`Data_Criacao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Data_Exclusao\` timestamp(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Caixa\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ESTABELECIMENTO\` (\`ID_Estabelecimento\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`CNPJ\` varchar(18) NOT NULL, \`Telefone\` varchar(20) NULL, \`Endereco\` varchar(255) NULL, \`Codigo_Autoatendimento\` varchar(10) NULL, \`Tem_Autoatendimento\` tinyint NOT NULL DEFAULT 0, \`Mercado_Pago_Id\` varchar(255) NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Gerente_Responsavel\` int NULL, UNIQUE INDEX \`IDX_a15e54fa574124dbc4abd9650c\` (\`CNPJ\`), UNIQUE INDEX \`IDX_79dce4cf49163d518e9457f6b3\` (\`Codigo_Autoatendimento\`), UNIQUE INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` (\`ID_Gerente_Responsavel\`), PRIMARY KEY (\`ID_Estabelecimento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`COMANDA\` (\`ID_Comanda\` int NOT NULL AUTO_INCREMENT, \`Descricao\` varchar(100) NOT NULL, \`Status\` varchar(30) NOT NULL, \`Total\` decimal(10,2) NOT NULL, \`Valor_Desconto_Aplicado\` decimal(10,2) NULL, \`Tipo_Desconto_Aplicado\` varchar(30) NULL, \`Data_Abertura\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Estabelecimento\` int NULL, \`ID_Cupom_Aplicado\` int NULL, INDEX \`idx_comanda_est_status_data\` (\`ID_Estabelecimento\`, \`Status\`, \`Data_Abertura\`), PRIMARY KEY (\`ID_Comanda\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PEDIDO\` (\`ID_Pedido\` int NOT NULL AUTO_INCREMENT, \`Status\` varchar(30) NOT NULL, \`Observacao\` varchar(255) NULL, \`Cancelamento_Descricao\` varchar(255) NULL, \`Tipo_Atendimento\` varchar(30) NOT NULL, \`Data_Hora_Chegada\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Comanda\` int NULL, \`ID_Usuario_Cancelador\` int NULL, \`ID_Usuario_Criador\` int NULL, INDEX \`idx_pedido_comanda_status_data\` (\`ID_Comanda\`, \`Status\`, \`Data_Hora_Chegada\`), PRIMARY KEY (\`ID_Pedido\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ITEM_PEDIDO\` (\`ID_Item\` int NOT NULL AUTO_INCREMENT, \`ID_Variacao\` int NULL, \`Observacoes_Cliente\` varchar(255) NULL, \`Quantidade\` int NOT NULL, \`Preco_Unitario_Momento\` decimal(10,2) NOT NULL, \`Data_Criacao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Produto\` int NULL, \`ID_Pedido\` int NULL, PRIMARY KEY (\`ID_Item\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PRODUTO_VARIACAO\` (\`ID_Variacao\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Preco_Adicional\` decimal(10,2) NOT NULL, \`status\` varchar(30) NOT NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Produto\` int NULL, PRIMARY KEY (\`ID_Variacao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PRODUTO\` (\`ID_Produto\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Descricao\` varchar(255) NULL DEFAULT 1, \`Imagem\` longtext NULL, \`Estocavel\` tinyint NOT NULL, \`Status\` varchar(255) NOT NULL DEFAULT 'Ativo', \`Preco_Base\` decimal(10,2) NOT NULL, \`Data_Exclusao\` timestamp(6) NULL, \`ID_Categoria\` int NULL, PRIMARY KEY (\`ID_Produto\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CATEGORIA\` (\`ID_Categoria\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(50) NOT NULL, \`Imagem\` varchar(255) NULL, \`Status\` varchar(255) NOT NULL DEFAULT 'Ativa', \`Data_Exclusao\` timestamp(6) NULL, \`ID_Estabelecimento\` int NULL, PRIMARY KEY (\`ID_Categoria\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ADMIN\` (\`ID_Admin\` int NOT NULL AUTO_INCREMENT, \`Nome\` varchar(100) NOT NULL, \`Email\` varchar(100) NOT NULL, \`Senha\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_c4da08b5c493a1e6b98e881ea8\` (\`Email\`), PRIMARY KEY (\`ID_Admin\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`NOTA_FISCAL\` (\`ID_Nota\` int NOT NULL AUTO_INCREMENT, \`Numero_Nota\` varchar(50) NOT NULL, \`CPF_CNPJ_Cliente\` varchar(18) NULL, \`Status\` enum ('Autorizada', 'Cancelada', 'Erro') NOT NULL DEFAULT 'Autorizada', \`Valor_Total\` decimal(10,2) NOT NULL, \`Data_Emissao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Data_Exclusao\` timestamp(6) NULL, \`ID_Pagamento\` int NULL, \`ID_Estabelecimento\` int NULL, UNIQUE INDEX \`REL_53587e2175429674989f61da16\` (\`ID_Pagamento\`), PRIMARY KEY (\`ID_Nota\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`REFRESH_TOKEN_USUARIO\` (\`ID_Token\` int NOT NULL AUTO_INCREMENT, \`Token_Hash\` varchar(255) NOT NULL, \`Revogado\` tinyint NOT NULL DEFAULT 0, \`Expires_At\` timestamp NOT NULL, \`ID_Usuario\` int NULL, UNIQUE INDEX \`IDX_d6dda53827096a07aad62101cc\` (\`Token_Hash\`), PRIMARY KEY (\`ID_Token\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`REFRESH_TOKEN_ADMIN\` (\`ID_Token\` int NOT NULL AUTO_INCREMENT, \`Token_Hash\` varchar(255) NOT NULL, \`Revogado\` tinyint NOT NULL DEFAULT 0, \`Expires_At\` timestamp NOT NULL, \`ID_Admin\` int NULL, UNIQUE INDEX \`IDX_1bbcfdd46195c3d8f5b6c18013\` (\`Token_Hash\`), PRIMARY KEY (\`ID_Token\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` (\`ID_Historico\` int NOT NULL AUTO_INCREMENT, \`ID_MP_Pagamento\` varchar(255) NOT NULL, \`Valor\` decimal(10,2) NOT NULL, \`Status\` enum ('Aprovado', 'Rejeitado') NOT NULL, \`Tipo_Pagamento\` varchar(50) NULL, \`Nome_Plano\` varchar(255) NOT NULL, \`Data_Pagamento\` datetime NULL, \`Data_Criacao\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ID_Assinatura\` int NULL, UNIQUE INDEX \`IDX_4dbbb5ab8056e7f1108e5c0270\` (\`ID_MP_Pagamento\`), PRIMARY KEY (\`ID_Historico\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`CARGO_PERMISSAO\` (\`ID_Cargo\` int NOT NULL, \`Nome_Permissao\` varchar(50) NOT NULL, INDEX \`IDX_16626de20fd06d374be6ddccfe\` (\`ID_Cargo\`), INDEX \`IDX_08ba26ce72dc5e2eea3e7b0ace\` (\`Nome_Permissao\`), PRIMARY KEY (\`ID_Cargo\`, \`Nome_Permissao\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` (\`ID_Estabelecimento\` int NOT NULL, \`ID_MetodoPagamento\` int NOT NULL, INDEX \`IDX_99270b5ecee09fce2c80aafd6c\` (\`ID_Estabelecimento\`), INDEX \`IDX_eb2f51c0c54c165cc0e62b5773\` (\`ID_MetodoPagamento\`), PRIMARY KEY (\`ID_Estabelecimento\`, \`ID_MetodoPagamento\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` ADD CONSTRAINT \`FK_94256e68a5d0c2294defa3f7022\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` ADD CONSTRAINT \`FK_8c186d01380c5905737f56e8489\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_acfd44433e0e71247c2c0f83605\` FOREIGN KEY (\`ID_Estoque_Item\`) REFERENCES \`ESTOQUE_ITEM\`(\`ID_Estoque_Item\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_57c345ee238785058affea4b5cd\` FOREIGN KEY (\`ID_Usuario_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_e1a1fa819701e6f06816a8b78c9\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_85ef99f6f9e459a32f2c2fd078a\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_d2ded8d86efaf8763b87f937654\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_7e6ba2c9056373e4c762799eaa3\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_bd6002cf64e5518daed0e85c68d\` FOREIGN KEY (\`ID_Usuario_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` ADD CONSTRAINT \`FK_8649b1a3e8b7befb4bbfa10fbbc\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD CONSTRAINT \`FK_5ab96b45f71c286111960f800ce\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_49ffbd5130542196a401fb27386\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_06a24908fb114bdb90d20d9f7da\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`FK_577007b2f099c57ac0a959d2345\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD CONSTRAINT \`FK_a42abc8787974640c8df84198c6\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` ADD CONSTRAINT \`FK_14bdd214a3cb4aa00dc17c75869\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`FK_28e1d2575f8a94cc6b4264c57b1\` FOREIGN KEY (\`ID_Gerente_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_6fd5f78c80915b4c9ef90a62f40\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_9fb026ed877c74180d4210a0805\` FOREIGN KEY (\`ID_Cupom_Aplicado\`) REFERENCES \`CUPOM_DESCONTO\`(\`ID_Cupom\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_a2419e69b50e597ce7e5a7df7e7\` FOREIGN KEY (\`ID_Comanda\`) REFERENCES \`COMANDA\`(\`ID_Comanda\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_5fea249bad2983b6781c52342fa\` FOREIGN KEY (\`ID_Usuario_Cancelador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_a76df1c02b24ad4cceb132fb730\` FOREIGN KEY (\`ID_Usuario_Criador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_d250e7a6b910ce68e7e6eeffc8a\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_dea4c4df3558a6bf4a799aa4773\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_dd767426078722c6880c3826a59\` FOREIGN KEY (\`ID_Variacao\`) REFERENCES \`PRODUTO_VARIACAO\`(\`ID_Variacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD CONSTRAINT \`FK_1343219e116bbb26b6a5097d62c\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD CONSTRAINT \`FK_711a41c3de8cfee194fa18b00eb\` FOREIGN KEY (\`ID_Categoria\`) REFERENCES \`CATEGORIA\`(\`ID_Categoria\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD CONSTRAINT \`FK_c28aee109023f1b56998424532f\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_53587e2175429674989f61da160\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_de876b1390cccda1e12da86d522\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` ADD CONSTRAINT \`FK_1ffbfd9d7d6f2fee07af19cba44\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` ADD CONSTRAINT \`FK_072911b2b621ad7e2e91b564f00\` FOREIGN KEY (\`ID_Admin\`) REFERENCES \`ADMIN\`(\`ID_Admin\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` ADD CONSTRAINT \`FK_0a6703d726a5ec9cad532bfd9a4\` FOREIGN KEY (\`ID_Assinatura\`) REFERENCES \`ASSINATURA\`(\`ID_Assinatura\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`FK_16626de20fd06d374be6ddccfe7\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`FK_08ba26ce72dc5e2eea3e7b0ace0\` FOREIGN KEY (\`Nome_Permissao\`) REFERENCES \`PERMISSAO\`(\`Nome\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`FK_99270b5ecee09fce2c80aafd6cd\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`FK_eb2f51c0c54c165cc0e62b57737\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE CASCADE ON UPDATE CASCADE`);

        await queryRunner.query(`INSERT INTO \`PERMISSAO\` (\`Nome\`) VALUES ('RELATORIOS'), ('COZINHA'), ('CARDAPIO'), ('FUNCIONARIOS'), ('CONFIGURACAO'), ('ASSINATURA'), ('CRIAR_PEDIDO'), ('NOTIFICACOES'), ('CAIXA'), ('COMANDAS_FINALIZADAS'), ('CUPONS'), ('NOTA_FISCAL')`);
        await queryRunner.query(`INSERT INTO \`METODO_PAGAMENTO\` (\`Nome\`) VALUES ('Dinheiro'), ('Débito'), ('Crédito'), ('Pix'), ('Vale Refeição')`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`FK_eb2f51c0c54c165cc0e62b57737\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`FK_99270b5ecee09fce2c80aafd6cd\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`FK_08ba26ce72dc5e2eea3e7b0ace0\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`FK_16626de20fd06d374be6ddccfe7\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` DROP FOREIGN KEY \`FK_0a6703d726a5ec9cad532bfd9a4\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` DROP FOREIGN KEY \`FK_072911b2b621ad7e2e91b564f00\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` DROP FOREIGN KEY \`FK_1ffbfd9d7d6f2fee07af19cba44\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_de876b1390cccda1e12da86d522\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_53587e2175429674989f61da160\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP FOREIGN KEY \`FK_c28aee109023f1b56998424532f\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP FOREIGN KEY \`FK_711a41c3de8cfee194fa18b00eb\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP FOREIGN KEY \`FK_1343219e116bbb26b6a5097d62c\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_dd767426078722c6880c3826a59\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_dea4c4df3558a6bf4a799aa4773\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_d250e7a6b910ce68e7e6eeffc8a\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_a76df1c02b24ad4cceb132fb730\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_5fea249bad2983b6781c52342fa\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_a2419e69b50e597ce7e5a7df7e7\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_9fb026ed877c74180d4210a0805\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_6fd5f78c80915b4c9ef90a62f40\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_28e1d2575f8a94cc6b4264c57b1\``);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` DROP FOREIGN KEY \`FK_14bdd214a3cb4aa00dc17c75869\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_a42abc8787974640c8df84198c6\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`FK_577007b2f099c57ac0a959d2345\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_06a24908fb114bdb90d20d9f7da\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_49ffbd5130542196a401fb27386\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP FOREIGN KEY \`FK_5ab96b45f71c286111960f800ce\``);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` DROP FOREIGN KEY \`FK_8649b1a3e8b7befb4bbfa10fbbc\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_bd6002cf64e5518daed0e85c68d\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_7e6ba2c9056373e4c762799eaa3\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_d2ded8d86efaf8763b87f937654\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_85ef99f6f9e459a32f2c2fd078a\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_e1a1fa819701e6f06816a8b78c9\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_57c345ee238785058affea4b5cd\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_acfd44433e0e71247c2c0f83605\``);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` DROP FOREIGN KEY \`FK_8c186d01380c5905737f56e8489\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` DROP FOREIGN KEY \`FK_94256e68a5d0c2294defa3f7022\``);
        await queryRunner.query(`DROP INDEX \`IDX_eb2f51c0c54c165cc0e62b5773\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_99270b5ecee09fce2c80aafd6c\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_08ba26ce72dc5e2eea3e7b0ace\` ON \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP INDEX \`IDX_16626de20fd06d374be6ddccfe\` ON \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP TABLE \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP INDEX \`IDX_4dbbb5ab8056e7f1108e5c0270\` ON \`HISTORICO_PAGAMENTO_ASSINATURA\``);
        await queryRunner.query(`DROP TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`IDX_1bbcfdd46195c3d8f5b6c18013\` ON \`REFRESH_TOKEN_ADMIN\``);
        await queryRunner.query(`DROP TABLE \`REFRESH_TOKEN_ADMIN\``);
        await queryRunner.query(`DROP INDEX \`IDX_d6dda53827096a07aad62101cc\` ON \`REFRESH_TOKEN_USUARIO\``);
        await queryRunner.query(`DROP TABLE \`REFRESH_TOKEN_USUARIO\``);
        await queryRunner.query(`DROP INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP TABLE \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`IDX_c4da08b5c493a1e6b98e881ea8\` ON \`ADMIN\``);
        await queryRunner.query(`DROP TABLE \`ADMIN\``);
        await queryRunner.query(`DROP TABLE \`CATEGORIA\``);
        await queryRunner.query(`DROP TABLE \`PRODUTO\``);
        await queryRunner.query(`DROP TABLE \`PRODUTO_VARIACAO\``);
        await queryRunner.query(`DROP TABLE \`ITEM_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`idx_pedido_comanda_status_data\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP TABLE \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`idx_comanda_est_status_data\` ON \`COMANDA\``);
        await queryRunner.query(`DROP TABLE \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_79dce4cf49163d518e9457f6b3\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_a15e54fa574124dbc4abd9650c\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP TABLE \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP TABLE \`CAIXA\``);
        await queryRunner.query(`DROP TABLE \`CONFIGURACAO_ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP TABLE \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP INDEX \`REL_49ffbd5130542196a401fb2738\` ON \`ASSINATURA\``);
        await queryRunner.query(`DROP TABLE \`ASSINATURA\``);
        await queryRunner.query(`DROP TABLE \`PLANO\``);
        await queryRunner.query(`DROP INDEX \`IDX_b588f17ba2b208199bbaae42ae\` ON \`USUARIO\``);
        await queryRunner.query(`DROP TABLE \`USUARIO\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc863aecc30115a2deffd1f674\` ON \`PERFIL_GERENTE\``);
        await queryRunner.query(`DROP TABLE \`PERFIL_GERENTE\``);
        await queryRunner.query(`DROP INDEX \`idx_pagamento_est_status_data\` ON \`PAGAMENTO\``);
        await queryRunner.query(`DROP TABLE \`PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_58f21eb039d1bcfa59d4be7a0f\` ON \`METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP TABLE \`METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP TABLE \`PAGAMENTO_PEDIDO\``);
        await queryRunner.query(`DROP TABLE \`MOVIMENTACAO_ESTOQUE\``);
        await queryRunner.query(`DROP INDEX \`REL_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\``);
        await queryRunner.query(`DROP TABLE \`ESTOQUE_ITEM\``);
        await queryRunner.query(`DROP TABLE \`CARGO\``);
        await queryRunner.query(`DROP TABLE \`PERMISSAO\``);
    }

}
