import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDb1781734613129 implements MigrationInterface {
    name = 'InitDb1781734613129'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`CARGO\` DROP FOREIGN KEY \`CARGO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` DROP FOREIGN KEY \`ESTOQUE_ITEM_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`MOVIMENTACAO_ESTOQUE_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`MOVIMENTACAO_ESTOQUE_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`MOVIMENTACAO_ESTOQUE_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`PAGAMENTO_PEDIDO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`PAGAMENTO_PEDIDO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`PAGAMENTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`PAGAMENTO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`PAGAMENTO_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`PAGAMENTO_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` DROP FOREIGN KEY \`PERFIL_GERENTE_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` DROP FOREIGN KEY \`PERFIL_GERENTE_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP FOREIGN KEY \`USUARIO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`FUNCIONALIDADE_PLANO\` DROP FOREIGN KEY \`FUNCIONALIDADE_PLANO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`ASSINATURA_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`ASSINATURA_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`ASSINATURA_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`CUPOM_DESCONTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`CUPOM_DESCONTO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP FOREIGN KEY \`CONFIGURACAO_ESTABELECIMENTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` DROP FOREIGN KEY \`CAIXA_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`ESTABELECIMENTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`COMANDA_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`COMANDA_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`COMANDA_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`COMANDA_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`PEDIDO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`PEDIDO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`PEDIDO_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`PEDIDO_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`ITEM_PEDIDO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`ITEM_PEDIDO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`ITEM_PEDIDO_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP FOREIGN KEY \`PRODUTO_VARIACAO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP FOREIGN KEY \`PRODUTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP FOREIGN KEY \`CATEGORIA_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`NOTA_FISCAL_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`NOTA_FISCAL_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` DROP FOREIGN KEY \`REFRESH_TOKEN_USUARIO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` DROP FOREIGN KEY \`REFRESH_TOKEN_ADMIN_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` DROP FOREIGN KEY \`HISTORICO_PAGAMENTO_ASSINATURA_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` DROP FOREIGN KEY \`HISTORICO_PAGAMENTO_ASSINATURA_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`CARGO_PERMISSAO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`CARGO_PERMISSAO_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`ESTABELECIMENTO_METODO_PAGAMENTO_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`ESTABELECIMENTO_METODO_PAGAMENTO_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`ID_Estabelecimento\` ON \`CARGO\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\``);
        await queryRunner.query(`DROP INDEX \`UK_TipoMovimentacao_Nome\` ON \`TIPO_MOVIMENTACAO\``);
        await queryRunner.query(`DROP INDEX \`ID_Estoque_Item\` ON \`MOVIMENTACAO_ESTOQUE\``);
        await queryRunner.query(`DROP INDEX \`ID_TipoMovimentacao\` ON \`MOVIMENTACAO_ESTOQUE\``);
        await queryRunner.query(`DROP INDEX \`ID_Usuario_Responsavel\` ON \`MOVIMENTACAO_ESTOQUE\``);
        await queryRunner.query(`DROP INDEX \`ID_Pagamento\` ON \`PAGAMENTO_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusPagamento_Nome\` ON \`STATUS_PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`ID_MetodoPagamento\` ON \`PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`ID_Usuario_Caixa\` ON \`PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`ID_Endereco\` ON \`PERFIL_GERENTE\``);
        await queryRunner.query(`DROP INDEX \`UQ_PerfilGerente_CPF\` ON \`PERFIL_GERENTE\``);
        await queryRunner.query(`DROP INDEX \`ID_Cargo\` ON \`USUARIO\``);
        await queryRunner.query(`DROP INDEX \`ID_Plano\` ON \`FUNCIONALIDADE_PLANO\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusAssinatura_Nome\` ON \`STATUS_ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`ID_Plano\` ON \`ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`IDX_49ffbd5130542196a401fb2738\` ON \`ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`UK_TipoDesconto_Nome\` ON \`TIPO_DESCONTO\``);
        await queryRunner.query(`DROP INDEX \`ID_TipoDesconto\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP INDEX \`ID_Estabelecimento\` ON \`CAIXA\``);
        await queryRunner.query(`DROP INDEX \`ID_Endereco\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusComanda_Nome\` ON \`STATUS_COMANDA\``);
        await queryRunner.query(`DROP INDEX \`ID_Cupom_Aplicado\` ON \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`ID_Tipo_Desconto_Aplicado\` ON \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusPedido_Nome\` ON \`STATUS_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Usuario_Cancelador\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Usuario_Criador\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Pedido\` ON \`ITEM_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Produto\` ON \`ITEM_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Variacao\` ON \`ITEM_PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`ID_Produto\` ON \`PRODUTO_VARIACAO\``);
        await queryRunner.query(`DROP INDEX \`ID_Categoria\` ON \`PRODUTO\``);
        await queryRunner.query(`DROP INDEX \`ID_Estabelecimento\` ON \`CATEGORIA\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusNotaFiscal_Nome\` ON \`STATUS_NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`IDX_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`ID_Usuario\` ON \`REFRESH_TOKEN_USUARIO\``);
        await queryRunner.query(`DROP INDEX \`ID_Admin\` ON \`REFRESH_TOKEN_ADMIN\``);
        await queryRunner.query(`DROP INDEX \`UK_StatusHistorico_Nome\` ON \`STATUS_HISTORICO_ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`ID_Assinatura\` ON \`HISTORICO_PAGAMENTO_ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`ID_Status\` ON \`HISTORICO_PAGAMENTO_ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`Nome_Permissao\` ON \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP INDEX \`ID_MetodoPagamento\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` CHANGE \`Data_Exclusao\` \`Data_Exclusao\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` CHANGE \`ID_Produto\` \`ID_Produto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` ADD UNIQUE INDEX \`IDX_8c186d01380c5905737f56e848\` (\`ID_Produto\`)`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP COLUMN \`Data_Criacao\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD \`Data_Criacao\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`DROP INDEX \`idx_pagamento_est_status_data\` ON \`PAGAMENTO\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_MetodoPagamento\` \`ID_MetodoPagamento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` CHANGE \`Ativo\` \`Ativo\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD UNIQUE INDEX \`IDX_49ffbd5130542196a401fb2738\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`DROP INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_28e1d2575f8a94cc6b4264c57b1\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` CHANGE \`Data_Exclusao\` \`Data_Exclusao\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD UNIQUE INDEX \`IDX_28e1d2575f8a94cc6b4264c57b\` (\`ID_Gerente_Responsavel\`)`);
        await queryRunner.query(`DROP INDEX \`idx_comanda_est_status_data\` ON \`COMANDA\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`DROP INDEX \`idx_pedido_comanda_status_data\` ON \`PEDIDO\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`ID_Comanda\` \`ID_Comanda\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` CHANGE \`ID_Produto\` \`ID_Produto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` CHANGE \`ID_Categoria\` \`ID_Categoria\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` CHANGE \`ID_Pagamento\` \`ID_Pagamento\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD UNIQUE INDEX \`IDX_53587e2175429674989f61da16\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` CHANGE \`ID_Status\` \`ID_Status\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\` (\`ID_Produto\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_pagamento_est_status_data\` ON \`PAGAMENTO\` (\`ID_Estabelecimento\`, \`ID_Status\`, \`Data_Hora_Pagamento\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_49ffbd5130542196a401fb2738\` ON \`ASSINATURA\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\` (\`ID_Estabelecimento\`, \`Codigo\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` ON \`ESTABELECIMENTO\` (\`ID_Gerente_Responsavel\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_comanda_est_status_data\` ON \`COMANDA\` (\`ID_Estabelecimento\`, \`ID_Status\`, \`Data_Abertura\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_pedido_comanda_status_data\` ON \`PEDIDO\` (\`ID_Comanda\`, \`ID_Status\`, \`Data_Hora_Chegada\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_16626de20fd06d374be6ddccfe\` ON \`CARGO_PERMISSAO\` (\`ID_Cargo\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_08ba26ce72dc5e2eea3e7b0ace\` ON \`CARGO_PERMISSAO\` (\`Nome_Permissao\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_99270b5ecee09fce2c80aafd6c\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_eb2f51c0c54c165cc0e62b5773\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\` (\`ID_MetodoPagamento\`)`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` ADD CONSTRAINT \`FK_94256e68a5d0c2294defa3f7022\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` ADD CONSTRAINT \`FK_8c186d01380c5905737f56e8489\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_58aeba39db67c1db45524d2ca5b\` FOREIGN KEY (\`ID_TipoMovimentacao\`) REFERENCES \`TIPO_MOVIMENTACAO\`(\`ID_TipoMovimentacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_acfd44433e0e71247c2c0f83605\` FOREIGN KEY (\`ID_Estoque_Item\`) REFERENCES \`ESTOQUE_ITEM\`(\`ID_Estoque_Item\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`FK_57c345ee238785058affea4b5cd\` FOREIGN KEY (\`ID_Usuario_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_e1a1fa819701e6f06816a8b78c9\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`FK_85ef99f6f9e459a32f2c2fd078a\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_d2ded8d86efaf8763b87f937654\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_8549fe667a3ddff584e575de757\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_PAGAMENTO\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_7e6ba2c9056373e4c762799eaa3\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`FK_bd6002cf64e5518daed0e85c68d\` FOREIGN KEY (\`ID_Usuario_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` ADD CONSTRAINT \`FK_ea8ba3199920b7ebf5af2b63b7b\` FOREIGN KEY (\`ID_Endereco\`) REFERENCES \`ENDERECO\`(\`ID_Endereco\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` ADD CONSTRAINT \`FK_8649b1a3e8b7befb4bbfa10fbbc\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD CONSTRAINT \`FK_5ab96b45f71c286111960f800ce\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`FUNCIONALIDADE_PLANO\` ADD CONSTRAINT \`FK_836976ce67dce5ab41cef8d6c2c\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_a57efc1f4a78ce11061f9e7030c\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_ASSINATURA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_49ffbd5130542196a401fb27386\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`FK_06a24908fb114bdb90d20d9f7da\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`FK_24763af9df97a879f334c119306\` FOREIGN KEY (\`ID_TipoDesconto\`) REFERENCES \`TIPO_DESCONTO\`(\`ID_TipoDesconto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`FK_577007b2f099c57ac0a959d2345\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD CONSTRAINT \`FK_a42abc8787974640c8df84198c6\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` ADD CONSTRAINT \`FK_14bdd214a3cb4aa00dc17c75869\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`FK_aa3f05f3097b68c93797802d277\` FOREIGN KEY (\`ID_Endereco\`) REFERENCES \`ENDERECO\`(\`ID_Endereco\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`FK_28e1d2575f8a94cc6b4264c57b1\` FOREIGN KEY (\`ID_Gerente_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_0f6fdc36bfe262649b00d118787\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_COMANDA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_f5ab68764852bab5460e15965e1\` FOREIGN KEY (\`ID_Tipo_Desconto_Aplicado\`) REFERENCES \`TIPO_DESCONTO\`(\`ID_TipoDesconto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_6fd5f78c80915b4c9ef90a62f40\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`FK_9fb026ed877c74180d4210a0805\` FOREIGN KEY (\`ID_Cupom_Aplicado\`) REFERENCES \`CUPOM_DESCONTO\`(\`ID_Cupom\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_535c51c3a9b71c4d9e3a4fdb3b9\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_PEDIDO\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_a2419e69b50e597ce7e5a7df7e7\` FOREIGN KEY (\`ID_Comanda\`) REFERENCES \`COMANDA\`(\`ID_Comanda\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_5fea249bad2983b6781c52342fa\` FOREIGN KEY (\`ID_Usuario_Cancelador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`FK_a76df1c02b24ad4cceb132fb730\` FOREIGN KEY (\`ID_Usuario_Criador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_d250e7a6b910ce68e7e6eeffc8a\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_dea4c4df3558a6bf4a799aa4773\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`FK_dd767426078722c6880c3826a59\` FOREIGN KEY (\`ID_Variacao\`) REFERENCES \`PRODUTO_VARIACAO\`(\`ID_Variacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD CONSTRAINT \`FK_1343219e116bbb26b6a5097d62c\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD CONSTRAINT \`FK_711a41c3de8cfee194fa18b00eb\` FOREIGN KEY (\`ID_Categoria\`) REFERENCES \`CATEGORIA\`(\`ID_Categoria\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD CONSTRAINT \`FK_c28aee109023f1b56998424532f\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_41812cf485f3b31792a068c9298\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_NOTA_FISCAL\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`FK_53587e2175429674989f61da160\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` ADD CONSTRAINT \`FK_1ffbfd9d7d6f2fee07af19cba44\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` ADD CONSTRAINT \`FK_072911b2b621ad7e2e91b564f00\` FOREIGN KEY (\`ID_Admin\`) REFERENCES \`ADMIN\`(\`ID_Admin\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` ADD CONSTRAINT \`FK_ce56031c3b84d8bb527d7e0391d\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_HISTORICO_ASSINATURA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` ADD CONSTRAINT \`FK_0a6703d726a5ec9cad532bfd9a4\` FOREIGN KEY (\`ID_Assinatura\`) REFERENCES \`ASSINATURA\`(\`ID_Assinatura\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`FK_16626de20fd06d374be6ddccfe7\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`FK_08ba26ce72dc5e2eea3e7b0ace0\` FOREIGN KEY (\`Nome_Permissao\`) REFERENCES \`PERMISSAO\`(\`Nome\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`FK_99270b5ecee09fce2c80aafd6cd\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`FK_eb2f51c0c54c165cc0e62b57737\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`FK_eb2f51c0c54c165cc0e62b57737\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` DROP FOREIGN KEY \`FK_99270b5ecee09fce2c80aafd6cd\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`FK_08ba26ce72dc5e2eea3e7b0ace0\``);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` DROP FOREIGN KEY \`FK_16626de20fd06d374be6ddccfe7\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` DROP FOREIGN KEY \`FK_0a6703d726a5ec9cad532bfd9a4\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` DROP FOREIGN KEY \`FK_ce56031c3b84d8bb527d7e0391d\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` DROP FOREIGN KEY \`FK_072911b2b621ad7e2e91b564f00\``);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` DROP FOREIGN KEY \`FK_1ffbfd9d7d6f2fee07af19cba44\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_53587e2175429674989f61da160\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP FOREIGN KEY \`FK_41812cf485f3b31792a068c9298\``);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` DROP FOREIGN KEY \`FK_c28aee109023f1b56998424532f\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` DROP FOREIGN KEY \`FK_711a41c3de8cfee194fa18b00eb\``);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` DROP FOREIGN KEY \`FK_1343219e116bbb26b6a5097d62c\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_dd767426078722c6880c3826a59\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_dea4c4df3558a6bf4a799aa4773\``);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` DROP FOREIGN KEY \`FK_d250e7a6b910ce68e7e6eeffc8a\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_a76df1c02b24ad4cceb132fb730\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_5fea249bad2983b6781c52342fa\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_a2419e69b50e597ce7e5a7df7e7\``);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` DROP FOREIGN KEY \`FK_535c51c3a9b71c4d9e3a4fdb3b9\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_9fb026ed877c74180d4210a0805\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_6fd5f78c80915b4c9ef90a62f40\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_f5ab68764852bab5460e15965e1\``);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` DROP FOREIGN KEY \`FK_0f6fdc36bfe262649b00d118787\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_28e1d2575f8a94cc6b4264c57b1\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_aa3f05f3097b68c93797802d277\``);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` DROP FOREIGN KEY \`FK_14bdd214a3cb4aa00dc17c75869\``);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` DROP FOREIGN KEY \`FK_a42abc8787974640c8df84198c6\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`FK_577007b2f099c57ac0a959d2345\``);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` DROP FOREIGN KEY \`FK_24763af9df97a879f334c119306\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_06a24908fb114bdb90d20d9f7da\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_49ffbd5130542196a401fb27386\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP FOREIGN KEY \`FK_a57efc1f4a78ce11061f9e7030c\``);
        await queryRunner.query(`ALTER TABLE \`FUNCIONALIDADE_PLANO\` DROP FOREIGN KEY \`FK_836976ce67dce5ab41cef8d6c2c\``);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` DROP FOREIGN KEY \`FK_5ab96b45f71c286111960f800ce\``);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` DROP FOREIGN KEY \`FK_8649b1a3e8b7befb4bbfa10fbbc\``);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` DROP FOREIGN KEY \`FK_ea8ba3199920b7ebf5af2b63b7b\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_bd6002cf64e5518daed0e85c68d\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_7e6ba2c9056373e4c762799eaa3\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_8549fe667a3ddff584e575de757\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` DROP FOREIGN KEY \`FK_d2ded8d86efaf8763b87f937654\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_85ef99f6f9e459a32f2c2fd078a\``);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` DROP FOREIGN KEY \`FK_e1a1fa819701e6f06816a8b78c9\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_57c345ee238785058affea4b5cd\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_acfd44433e0e71247c2c0f83605\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP FOREIGN KEY \`FK_58aeba39db67c1db45524d2ca5b\``);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` DROP FOREIGN KEY \`FK_8c186d01380c5905737f56e8489\``);
        await queryRunner.query(`ALTER TABLE \`CARGO\` DROP FOREIGN KEY \`FK_94256e68a5d0c2294defa3f7022\``);
        await queryRunner.query(`DROP INDEX \`IDX_eb2f51c0c54c165cc0e62b5773\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_99270b5ecee09fce2c80aafd6c\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`IDX_08ba26ce72dc5e2eea3e7b0ace\` ON \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP INDEX \`IDX_16626de20fd06d374be6ddccfe\` ON \`CARGO_PERMISSAO\``);
        await queryRunner.query(`DROP INDEX \`REL_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\``);
        await queryRunner.query(`DROP INDEX \`idx_pedido_comanda_status_data\` ON \`PEDIDO\``);
        await queryRunner.query(`DROP INDEX \`idx_comanda_est_status_data\` ON \`COMANDA\``);
        await queryRunner.query(`DROP INDEX \`REL_28e1d2575f8a94cc6b4264c57b\` ON \`ESTABELECIMENTO\``);
        await queryRunner.query(`DROP INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\``);
        await queryRunner.query(`DROP INDEX \`REL_49ffbd5130542196a401fb2738\` ON \`ASSINATURA\``);
        await queryRunner.query(`DROP INDEX \`idx_pagamento_est_status_data\` ON \`PAGAMENTO\``);
        await queryRunner.query(`DROP INDEX \`REL_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` DROP INDEX \`IDX_53587e2175429674989f61da16\``);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` CHANGE \`ID_Pagamento\` \`ID_Pagamento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` CHANGE \`ID_Categoria\` \`ID_Categoria\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` CHANGE \`ID_Produto\` \`ID_Produto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`ID_Comanda\` \`ID_Comanda\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_pedido_comanda_status_data\` ON \`PEDIDO\` (\`ID_Comanda\`, \`ID_Status\`, \`Data_Hora_Chegada\`)`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_comanda_est_status_data\` ON \`COMANDA\` (\`ID_Estabelecimento\`, \`ID_Status\`, \`Data_Abertura\`)`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` DROP INDEX \`IDX_28e1d2575f8a94cc6b4264c57b\``);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` CHANGE \`Data_Exclusao\` \`Data_Exclusao\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`FK_28e1d2575f8a94cc6b4264c57b1\` FOREIGN KEY (\`ID_Gerente_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_Estabelecimento_Codigo\` ON \`CUPOM_DESCONTO\` (\`ID_Estabelecimento\`, \`Codigo\`)`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` DROP INDEX \`IDX_49ffbd5130542196a401fb2738\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` CHANGE \`Ativo\` \`Ativo\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_Status\` \`ID_Status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` CHANGE \`ID_MetodoPagamento\` \`ID_MetodoPagamento\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_pagamento_est_status_data\` ON \`PAGAMENTO\` (\`ID_Estabelecimento\`, \`ID_Status\`, \`Data_Hora_Pagamento\`)`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` DROP COLUMN \`Data_Criacao\``);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD \`Data_Criacao\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` DROP INDEX \`IDX_8c186d01380c5905737f56e848\``);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` CHANGE \`ID_Produto\` \`ID_Produto\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` CHANGE \`ID_Estabelecimento\` \`ID_Estabelecimento\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` CHANGE \`Data_Exclusao\` \`Data_Exclusao\` timestamp(0) NULL`);
        await queryRunner.query(`CREATE INDEX \`ID_MetodoPagamento\` ON \`ESTABELECIMENTO_METODO_PAGAMENTO\` (\`ID_MetodoPagamento\`)`);
        await queryRunner.query(`CREATE INDEX \`Nome_Permissao\` ON \`CARGO_PERMISSAO\` (\`Nome_Permissao\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`HISTORICO_PAGAMENTO_ASSINATURA\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Assinatura\` ON \`HISTORICO_PAGAMENTO_ASSINATURA\` (\`ID_Assinatura\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusHistorico_Nome\` ON \`STATUS_HISTORICO_ASSINATURA\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Admin\` ON \`REFRESH_TOKEN_ADMIN\` (\`ID_Admin\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Usuario\` ON \`REFRESH_TOKEN_USUARIO\` (\`ID_Usuario\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_53587e2175429674989f61da16\` ON \`NOTA_FISCAL\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`NOTA_FISCAL\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusNotaFiscal_Nome\` ON \`STATUS_NOTA_FISCAL\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Estabelecimento\` ON \`CATEGORIA\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Categoria\` ON \`PRODUTO\` (\`ID_Categoria\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Produto\` ON \`PRODUTO_VARIACAO\` (\`ID_Produto\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Variacao\` ON \`ITEM_PEDIDO\` (\`ID_Variacao\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Produto\` ON \`ITEM_PEDIDO\` (\`ID_Produto\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Pedido\` ON \`ITEM_PEDIDO\` (\`ID_Pedido\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Usuario_Criador\` ON \`PEDIDO\` (\`ID_Usuario_Criador\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Usuario_Cancelador\` ON \`PEDIDO\` (\`ID_Usuario_Cancelador\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`PEDIDO\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusPedido_Nome\` ON \`STATUS_PEDIDO\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Tipo_Desconto_Aplicado\` ON \`COMANDA\` (\`ID_Tipo_Desconto_Aplicado\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`COMANDA\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Cupom_Aplicado\` ON \`COMANDA\` (\`ID_Cupom_Aplicado\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusComanda_Nome\` ON \`STATUS_COMANDA\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Endereco\` ON \`ESTABELECIMENTO\` (\`ID_Endereco\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Estabelecimento\` ON \`CAIXA\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_TipoDesconto\` ON \`CUPOM_DESCONTO\` (\`ID_TipoDesconto\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_TipoDesconto_Nome\` ON \`TIPO_DESCONTO\` (\`Nome\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_49ffbd5130542196a401fb2738\` ON \`ASSINATURA\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`ASSINATURA\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Plano\` ON \`ASSINATURA\` (\`ID_Plano\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusAssinatura_Nome\` ON \`STATUS_ASSINATURA\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Plano\` ON \`FUNCIONALIDADE_PLANO\` (\`ID_Plano\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Cargo\` ON \`USUARIO\` (\`ID_Cargo\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_PerfilGerente_CPF\` ON \`PERFIL_GERENTE\` (\`CPF\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Endereco\` ON \`PERFIL_GERENTE\` (\`ID_Endereco\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Usuario_Caixa\` ON \`PAGAMENTO\` (\`ID_Usuario_Caixa\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Status\` ON \`PAGAMENTO\` (\`ID_Status\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_MetodoPagamento\` ON \`PAGAMENTO\` (\`ID_MetodoPagamento\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_StatusPagamento_Nome\` ON \`STATUS_PAGAMENTO\` (\`Nome\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Pagamento\` ON \`PAGAMENTO_PEDIDO\` (\`ID_Pagamento\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Usuario_Responsavel\` ON \`MOVIMENTACAO_ESTOQUE\` (\`ID_Usuario_Responsavel\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_TipoMovimentacao\` ON \`MOVIMENTACAO_ESTOQUE\` (\`ID_TipoMovimentacao\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Estoque_Item\` ON \`MOVIMENTACAO_ESTOQUE\` (\`ID_Estoque_Item\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_TipoMovimentacao_Nome\` ON \`TIPO_MOVIMENTACAO\` (\`Nome\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_8c186d01380c5905737f56e848\` ON \`ESTOQUE_ITEM\` (\`ID_Produto\`)`);
        await queryRunner.query(`CREATE INDEX \`ID_Estabelecimento\` ON \`CARGO\` (\`ID_Estabelecimento\`)`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`ESTABELECIMENTO_METODO_PAGAMENTO_ibfk_2\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO_METODO_PAGAMENTO\` ADD CONSTRAINT \`ESTABELECIMENTO_METODO_PAGAMENTO_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`CARGO_PERMISSAO_ibfk_2\` FOREIGN KEY (\`Nome_Permissao\`) REFERENCES \`PERMISSAO\`(\`Nome\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`CARGO_PERMISSAO\` ADD CONSTRAINT \`CARGO_PERMISSAO_ibfk_1\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` ADD CONSTRAINT \`HISTORICO_PAGAMENTO_ASSINATURA_ibfk_2\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_HISTORICO_ASSINATURA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTO_ASSINATURA\` ADD CONSTRAINT \`HISTORICO_PAGAMENTO_ASSINATURA_ibfk_1\` FOREIGN KEY (\`ID_Assinatura\`) REFERENCES \`ASSINATURA\`(\`ID_Assinatura\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_ADMIN\` ADD CONSTRAINT \`REFRESH_TOKEN_ADMIN_ibfk_1\` FOREIGN KEY (\`ID_Admin\`) REFERENCES \`ADMIN\`(\`ID_Admin\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`REFRESH_TOKEN_USUARIO\` ADD CONSTRAINT \`REFRESH_TOKEN_USUARIO_ibfk_1\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`NOTA_FISCAL_ibfk_2\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_NOTA_FISCAL\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`NOTA_FISCAL\` ADD CONSTRAINT \`NOTA_FISCAL_ibfk_1\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CATEGORIA\` ADD CONSTRAINT \`CATEGORIA_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO\` ADD CONSTRAINT \`PRODUTO_ibfk_1\` FOREIGN KEY (\`ID_Categoria\`) REFERENCES \`CATEGORIA\`(\`ID_Categoria\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRODUTO_VARIACAO\` ADD CONSTRAINT \`PRODUTO_VARIACAO_ibfk_1\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`ITEM_PEDIDO_ibfk_3\` FOREIGN KEY (\`ID_Variacao\`) REFERENCES \`PRODUTO_VARIACAO\`(\`ID_Variacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`ITEM_PEDIDO_ibfk_2\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ITEM_PEDIDO\` ADD CONSTRAINT \`ITEM_PEDIDO_ibfk_1\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`PEDIDO_ibfk_4\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_PEDIDO\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`PEDIDO_ibfk_3\` FOREIGN KEY (\`ID_Usuario_Criador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`PEDIDO_ibfk_2\` FOREIGN KEY (\`ID_Usuario_Cancelador\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PEDIDO\` ADD CONSTRAINT \`PEDIDO_ibfk_1\` FOREIGN KEY (\`ID_Comanda\`) REFERENCES \`COMANDA\`(\`ID_Comanda\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`COMANDA_ibfk_4\` FOREIGN KEY (\`ID_Tipo_Desconto_Aplicado\`) REFERENCES \`TIPO_DESCONTO\`(\`ID_TipoDesconto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`COMANDA_ibfk_3\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_COMANDA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`COMANDA_ibfk_2\` FOREIGN KEY (\`ID_Cupom_Aplicado\`) REFERENCES \`CUPOM_DESCONTO\`(\`ID_Cupom\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`COMANDA\` ADD CONSTRAINT \`COMANDA_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTABELECIMENTO\` ADD CONSTRAINT \`ESTABELECIMENTO_ibfk_1\` FOREIGN KEY (\`ID_Endereco\`) REFERENCES \`ENDERECO\`(\`ID_Endereco\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CAIXA\` ADD CONSTRAINT \`CAIXA_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CONFIGURACAO_ESTABELECIMENTO\` ADD CONSTRAINT \`CONFIGURACAO_ESTABELECIMENTO_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`CUPOM_DESCONTO_ibfk_2\` FOREIGN KEY (\`ID_TipoDesconto\`) REFERENCES \`TIPO_DESCONTO\`(\`ID_TipoDesconto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CUPOM_DESCONTO\` ADD CONSTRAINT \`CUPOM_DESCONTO_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`ASSINATURA_ibfk_3\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_ASSINATURA\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`ASSINATURA_ibfk_2\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURA\` ADD CONSTRAINT \`ASSINATURA_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`FUNCIONALIDADE_PLANO\` ADD CONSTRAINT \`FUNCIONALIDADE_PLANO_ibfk_1\` FOREIGN KEY (\`ID_Plano\`) REFERENCES \`PLANO\`(\`ID_Plano\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`USUARIO\` ADD CONSTRAINT \`USUARIO_ibfk_1\` FOREIGN KEY (\`ID_Cargo\`) REFERENCES \`CARGO\`(\`ID_Cargo\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` ADD CONSTRAINT \`PERFIL_GERENTE_ibfk_2\` FOREIGN KEY (\`ID_Endereco\`) REFERENCES \`ENDERECO\`(\`ID_Endereco\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PERFIL_GERENTE\` ADD CONSTRAINT \`PERFIL_GERENTE_ibfk_1\` FOREIGN KEY (\`ID_Usuario\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`PAGAMENTO_ibfk_4\` FOREIGN KEY (\`ID_Status\`) REFERENCES \`STATUS_PAGAMENTO\`(\`ID_Status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`PAGAMENTO_ibfk_3\` FOREIGN KEY (\`ID_MetodoPagamento\`) REFERENCES \`METODO_PAGAMENTO\`(\`ID_MetodoPagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`PAGAMENTO_ibfk_2\` FOREIGN KEY (\`ID_Usuario_Caixa\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO\` ADD CONSTRAINT \`PAGAMENTO_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`PAGAMENTO_PEDIDO_ibfk_2\` FOREIGN KEY (\`ID_Pedido\`) REFERENCES \`PEDIDO\`(\`ID_Pedido\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PAGAMENTO_PEDIDO\` ADD CONSTRAINT \`PAGAMENTO_PEDIDO_ibfk_1\` FOREIGN KEY (\`ID_Pagamento\`) REFERENCES \`PAGAMENTO\`(\`ID_Pagamento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`MOVIMENTACAO_ESTOQUE_ibfk_3\` FOREIGN KEY (\`ID_TipoMovimentacao\`) REFERENCES \`TIPO_MOVIMENTACAO\`(\`ID_TipoMovimentacao\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`MOVIMENTACAO_ESTOQUE_ibfk_2\` FOREIGN KEY (\`ID_Usuario_Responsavel\`) REFERENCES \`USUARIO\`(\`ID_Usuario\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MOVIMENTACAO_ESTOQUE\` ADD CONSTRAINT \`MOVIMENTACAO_ESTOQUE_ibfk_1\` FOREIGN KEY (\`ID_Estoque_Item\`) REFERENCES \`ESTOQUE_ITEM\`(\`ID_Estoque_Item\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ESTOQUE_ITEM\` ADD CONSTRAINT \`ESTOQUE_ITEM_ibfk_1\` FOREIGN KEY (\`ID_Produto\`) REFERENCES \`PRODUTO\`(\`ID_Produto\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`CARGO\` ADD CONSTRAINT \`CARGO_ibfk_1\` FOREIGN KEY (\`ID_Estabelecimento\`) REFERENCES \`ESTABELECIMENTO\`(\`ID_Estabelecimento\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
