export const PERMISSIONS = {
  RELATORIOS: 'RELATORIOS',
  COZINHA: 'COZINHA',
  ESTOQUE: 'ESTOQUE',
  CARDAPIO: 'CARDAPIO',
  FUNCIONARIOS: 'FUNCIONARIOS',
  CONFIGURACAO: 'CONFIGURACAO',
  ASSINATURA: 'ASSINATURA',
  CRIAR_PEDIDO: 'CRIAR_PEDIDO',
  NOTIFICACOES: 'NOTIFICACOES'
};